// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDohz8eM_rxk7f27VqtILh69u5shCAAD0M',
    appId: '1:852281483169:web:4742cde7ed9dc9a4a075e0',
    messagingSenderId: '852281483169',
    projectId: 'fintrack-flutter',
    authDomain: 'fintrack-flutter.firebaseapp.com',
    storageBucket: 'fintrack-flutter.firebasestorage.app',
    measurementId: 'G-TEKRXY266T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEf7UGHUzS8zOuZ52qKcAavBILh6c9N9U',
    appId: '1:852281483169:android:31465b19b382b804a075e0',
    messagingSenderId: '852281483169',
    projectId: 'fintrack-flutter',
    storageBucket: 'fintrack-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl80SbfZAhcuPJQi71vGeK8EZp91kVSys',
    appId: '1:852281483169:ios:4ec54c79351f6347a075e0',
    messagingSenderId: '852281483169',
    projectId: 'fintrack-flutter',
    storageBucket: 'fintrack-flutter.firebasestorage.app',
    iosClientId: '852281483169-kihhd5o0l2b0udkhe14un2sav9lpch1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl80SbfZAhcuPJQi71vGeK8EZp91kVSys',
    appId: '1:852281483169:ios:4ec54c79351f6347a075e0',
    messagingSenderId: '852281483169',
    projectId: 'fintrack-flutter',
    storageBucket: 'fintrack-flutter.firebasestorage.app',
    iosClientId: '852281483169-kihhd5o0l2b0udkhe14un2sav9lpch1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDohz8eM_rxk7f27VqtILh69u5shCAAD0M',
    appId: '1:852281483169:web:3427a9f40e3e23ada075e0',
    messagingSenderId: '852281483169',
    projectId: 'fintrack-flutter',
    authDomain: 'fintrack-flutter.firebaseapp.com',
    storageBucket: 'fintrack-flutter.firebasestorage.app',
    measurementId: 'G-C75B27F0C9',
  );
}
